# Generated by Django 2.1.4 on 2019-01-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190104_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='trip_number',
            field=models.URLField(default=None),
        ),
    ]
