# Generated by Django 2.1.4 on 2019-01-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190104_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='trip_number',
        ),
        migrations.AddField(
            model_name='home',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
