# Generated by Django 2.1.7 on 2019-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.ImageField(upload_to='check_image'),
        ),
    ]
