# Generated by Django 2.1.4 on 2019-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='trip_number',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Trip Number'),
        ),
    ]
