# Generated by Django 2.1.4 on 2019-01-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_home_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
