# Generated by Django 2.1.4 on 2019-01-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_home_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to='post_thumbnails'),
        ),
    ]
