# Generated by Django 2.1.7 on 2019-02-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190105_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
